# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MiSleep\gui\MiSleep\spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spectrum(object):
    def setupUi(self, spectrum):
        spectrum.setObjectName("spectrum")
        spectrum.resize(1092, 700)
        spectrum.setMinimumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/.png/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        spectrum.setWindowIcon(icon)
        spectrum.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(spectrum)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeFrequencyArea = QtWidgets.QScrollArea(spectrum)
        self.timeFrequencyArea.setWidgetResizable(True)
        self.timeFrequencyArea.setObjectName("timeFrequencyArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1072, 305))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.timeFrequencyArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.timeFrequencyArea)
        self.saveTFBt = QtWidgets.QPushButton(spectrum)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.saveTFBt.setFont(font)
        self.saveTFBt.setObjectName("saveTFBt")
        self.verticalLayout.addWidget(self.saveTFBt)
        self.spectrumArea = QtWidgets.QScrollArea(spectrum)
        self.spectrumArea.setWidgetResizable(True)
        self.spectrumArea.setObjectName("spectrumArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1072, 305))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.spectrumArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.spectrumArea)
        self.saveSpectrumBt = QtWidgets.QPushButton(spectrum)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.saveSpectrumBt.setFont(font)
        self.saveSpectrumBt.setObjectName("saveSpectrumBt")
        self.verticalLayout.addWidget(self.saveSpectrumBt)

        self.retranslateUi(spectrum)
        QtCore.QMetaObject.connectSlotsByName(spectrum)

    def retranslateUi(self, spectrum):
        _translate = QtCore.QCoreApplication.translate
        spectrum.setWindowTitle(_translate("spectrum", "Spectrum"))
        self.saveTFBt.setText(_translate("spectrum", "Save"))
        self.saveSpectrumBt.setText(_translate("spectrum", "Save"))
from MiSleep.imgs import img_rc
